import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fontAll = localFont({
  src: "../public/assets/font/Machi.ttf",
  variable: "--all-font",
});
const fontTitle = localFont({
  src: "../public/assets/font/divlit001.ttf",
  variable: "--title-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontAll.variable} ${fontTitle.variable}`}>
        {children}
      </body>
    </html>
  );
}
