import type { Metadata } from "next";
import localFont from "next/font/local";
import { Exo } from "next/font/google";
import "./globals.css";
import Loading from "@/components/ui/loader";
import ToastProvider from "@/providers/toast-provider";
import AuthProvider from "@/providers/next-auth-session";
import CursorProvider from "@/providers/cursor-cursor";
import ContextDisableProvider from "@/providers/context-provider";

const fontAll = localFont({
  src: "../public/assets/font/Machi.ttf",
  variable: "--all-font",
});
const fontTitle = localFont({
  src: "../public/assets/font/divlit001.ttf",
  variable: "--title-font",
});
const fontExo = Exo({
  style: "normal",
  weight: "400",
  subsets: ["latin"],
  variable: "--exo-font",
});
export const metadata: Metadata = {
  title: "Gemisha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <ContextDisableProvider>
          <body
            className={`${fontAll.variable} ${fontExo.variable} ${fontTitle.variable}`}
          >
            <CursorProvider />
            <Loading />
            {children}
            <ToastProvider />
          </body>
        </ContextDisableProvider>
      </html>
    </AuthProvider>
  );
}
